// frontend/src/components/Board.tsx
/* src/components/Board.tsx */
import React from "react";
import { Cell } from "./Cell";
import { CellInfo } from "@/types/game";
import "@/styles/board.css";

type Props = {
    board: CellInfo[][];
    onCellClick: (r: number, c: number) => void;
    flagged: Set<string>;
    toggleFlag: (r: number, c: number) => void;
};

export const Board: React.FC<Props> = ({
    board,
    onCellClick,
    flagged,
    toggleFlag,
}) => {
    const cols = board[0]?.length ?? 0;

    return (
        <div
            className="board"
            style={
                cols
                    ? {
                          gridTemplateColumns: `repeat(${cols}, var(--cell-size))`,
                      }
                    : undefined
            }
        >
            {board.map((row, r) => (
                <div className="row" key={r}>
                    {row.map((cell, c) => (
                        <Cell
                            key={`${r}-${c}`}
                            cell={cell}
                            isFlagged={flagged.has(`${r}-${c}`)}
                            onClick={() => onCellClick(r, c)}
                            onRightClick={() => toggleFlag(r, c)}
                        />
                    ))}
                </div>
            ))}
        </div>
    );
};

// frontend_vue/src/components/Board.vue
<template>
    <div
      class="board"
      :style="{
        gridTemplateColumns: `repeat(${board[0]?.length || 0}, var(--cell-size))`,
      }"
    >
      <div v-for="(row, r) in board" :key="r" class="board-row">
        <Cell
          v-for="(cell, c) in row"
          :key="`${r}-${c}`"
          :cell="cell"
          :is-flagged="flagged.has(`${r}-${c}`)"
          @click="() => onCellClick(r, c)"
          @right-click="() => toggleFlag(r, c)"
        ></Cell>
      </div>
    </div>
  </template>
  
  <script setup lang="ts">
  import { defineProps } from "vue";
  import Cell from "./Cell.vue";
  import type { CellInfo } from "@/types/game";
  
  const props = defineProps<{
    board: CellInfo[][];
    flagged: Set<string>;
    onCellClick: (r: number, c: number) => void;
    toggleFlag: (r: number, c: number) => void;
  }>();
  </script>
  
  <style scoped>
  .board {
    display: grid;
    gap: var(--cell-gap);
    justify-content: center;
    grid-auto-rows: var(--cell-size);
  }
  .board-row {
    display: contents; /* Ensures proper grid formatting */
  }
  </style>
